services:
  # --- GITLAB COMMUNITY EDITION ---
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - './volumes/gitlab/config:/etc/gitlab'
      - './volumes/gitlab/logs:/var/log/gitlab'
      - './volumes/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      default:
        ipv4_address: 172.20.0.10

  # --- GITLAB RUNNER ---
  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - './volumes/runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - default

  # --- DEPENDENCY-TRACK API SERVER ---
  dtrack-api:
    image: dependencytrack/apiserver
    container_name: dtrack-api
    ports:
      - "8081:8080"
    environment:
      - ALPINE_DATABASE_MODE=embedded
    volumes:
      - './volumes/dtrack:/data'
    networks:
      - default

  # --- DEPENDENCY-TRACK FRONTEND ---
  dtrack-ui:
    image: dependencytrack/frontend
    container_name: dtrack-ui
    depends_on:
      - dtrack-api
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://localhost:8081
    networks:
      - default

networks:
  default:
    name: talk-sbom-sbam_default
    ipam:
      config:
        - subnet: 172.20.0.0/24